### ISSUE TITLE
Getting "KeyError: (0, 0, 12)" while exporting materials using the last release

### ISSUE THREAD

**Issue by chianti-ga** [koerismo/PBR-2-Source#8]
Hi, i'm getting this error using the last version (v2.0.3-beta) on windows:

```
Exporting...
Constructing material...
Picking target
Export: Processing textures...
Export: Making VMT...
Export: Writing files...
The export failed!

 Traceback (most recent call last):
  File "module\gui\__init__.py", line 412, in export
  File "module\gui\backend.py", line 188, in export
  File "module\core\io\image.py", line 137, in save
  File "module\core\io\qtio.py", line 87, in save
  File "srctools\vtf.py", line 1066, in get
KeyError: (0, 0, 12)```

**Comment by koerismo** [comment]
This should be patched in v2.0.4-beta.
